// 修改段落
export const CHANGE_PARAGRAGH_DATA = 'CHANGE_PARAGRAGH_DATA'

// 修改标题
export const CHANGE_CONTENT_TITLE = 'CHANGE_CONTENT_TITLE'
export const CHANGE_CONTENT_POI_LIST = 'CHANGE_CONTENT_POI_LIST'
export const CHANGE_CONTENT_TAG_LIST = 'CHANGE_CONTENT_TAG_LIST'

export const EDITOR_CONTENT_CLEAR = 'EDITOR_CONTENT_CLEAR'
